<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>8d36a03e-ca49-42bd-bc28-86f3874d5b32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.pjAcceptCookieBarBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e1d066d-d107-41e9-8e72-ebd5bad4a1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>06b4ce57-e8d0-44b8-b471-0d10bdb217dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pjAcceptCookieBarBtn</value>
      <webElementGuid>4d9cf6bb-0704-463e-b80e-8417e2ae04a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ยอมรับ</value>
      <webElementGuid>2de80cee-06f0-4e63-a9bd-3d5e5121d2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pjAcceptCookieBar&quot;)/div[@class=&quot;pjAcceptCookieBarShell&quot;]/form[1]/p[1]/button[@class=&quot;pjAcceptCookieBarBtn&quot;]</value>
      <webElementGuid>d41f3c5e-92db-44df-81ed-60006fedec21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>041e48d4-fb94-47e6-a378-ece1b0313a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pjAcceptCookieBar']/div/form/p/button</value>
      <webElementGuid>c6f59364-8e80-41e1-9d00-40cf3e966056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='อ่านเพิ่มเติม'])[1]/following::button[1]</value>
      <webElementGuid>a463b766-3e81-4ad1-8fda-39dba43292ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', '&quot;', 'ยอมรับ', '&quot;', ' หรือใช้งานเว็บไซต์ของเราต่อ')])[1]/following::button[1]</value>
      <webElementGuid>1fe3f700-76b7-43d8-84df-e84485ac03ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ยอมรับ']/parent::*</value>
      <webElementGuid>20bd8c62-b397-4df4-a8d5-fce1d3994331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>669029cd-ea9a-4f6d-934e-6fd1676e38f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'ยอมรับ' or . = 'ยอมรับ')]</value>
      <webElementGuid>27e279f6-ab7a-4843-82d4-326d1e5a9f11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
