<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__field_reg_company_nameund0value</name>
   <tag></tag>
   <elementGuidId>c2e08ee6-17f4-404b-8be7-df671ffa2f27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-field-reg-company-name-und-0-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit-field-reg-company-name-und-0-value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>982332ef-d433-441f-81dd-f794114d03e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-full form-text</value>
      <webElementGuid>7793f03a-b7b0-4909-af38-347f4e3cf253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>565e1b1d-e21d-4191-a8a1-f36196a65bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-field-reg-company-name-und-0-value</value>
      <webElementGuid>9fe4ae14-27b5-4fec-b712-ed6024452a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_reg_company_name[und][0][value]</value>
      <webElementGuid>ca42fac8-2101-4c7e-832d-4b2e848360e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>21e5d0d1-fcde-4734-8070-93319337f67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>dc5f112b-1207-4ace-9d9e-dc08e582e72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-field-reg-company-name-und-0-value&quot;)</value>
      <webElementGuid>20bf06ec-33a2-4ff1-a98e-4a5c7f2aaf94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-field-reg-company-name-und-0-value']</value>
      <webElementGuid>75729377-2198-4278-a830-34b1af193204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-reg-company-name-add-more-wrapper']/div/input</value>
      <webElementGuid>576102b5-d7d6-41fb-86d4-8ac7c410c77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>2e2f7fd9-8425-4842-a0d2-46c3bc8a76c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'edit-field-reg-company-name-und-0-value' and @name = 'field_reg_company_name[und][0][value]']</value>
      <webElementGuid>7f92041b-e3d3-4553-8556-2d55d33b86e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
