<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__field_reg_emailund0email</name>
   <tag></tag>
   <elementGuidId>ec886e7d-dd2b-4ce6-a237-549944151bf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-field-reg-email-und-0-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit-field-reg-email-und-0-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8ce7077-0815-47e1-ac2f-5df1ffcbcb27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9e9cd5ba-a943-4f8d-95ba-583bf99154ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-field-reg-email-und-0-email</value>
      <webElementGuid>c1b879e9-1829-425d-8f40-19ac7ed34df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_reg_email[und][0][email]</value>
      <webElementGuid>0cc19563-7dca-45bd-8a98-50c9ce7874a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>ba3731d2-5107-4099-838b-ac5b52b6a215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>e9e488a5-9a8f-467c-b4a1-e35b12657fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-text required</value>
      <webElementGuid>1ad48ea4-7bd5-40e0-868c-df37ec910e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-field-reg-email-und-0-email&quot;)</value>
      <webElementGuid>9ab4ca4e-ba07-4c4d-b88e-298e5773c952</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-field-reg-email-und-0-email']</value>
      <webElementGuid>deccf6fb-767e-4452-b37b-f7872012d89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-reg-email-add-more-wrapper']/div/div/input</value>
      <webElementGuid>9d6ef67c-5a97-496b-a81f-4e359976f5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/input</value>
      <webElementGuid>cb90a232-2907-443a-9376-d9ae78f57876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'edit-field-reg-email-und-0-email' and @name = 'field_reg_email[und][0][email]']</value>
      <webElementGuid>80467942-d9df-4578-8140-90ef40dd07f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
