<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__captcha_response</name>
   <tag></tag>
   <elementGuidId>317d6fbc-5ee3-48dd-8808-b82d4e96134f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-captcha-response</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit-captcha-response']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74285270-abc8-4df7-876d-6784e291b3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0dd9e6f9-f0da-4bdb-ae87-3dd0ac53e46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-captcha-response</value>
      <webElementGuid>567fdb7a-ce69-4b1b-9266-f30437ad74b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>captcha_response</value>
      <webElementGuid>deba15ca-f212-43b3-9b5a-06213cc93e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>1ab60635-9d78-4fa8-9843-3787b52eb32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>351e482a-438b-4795-a5bc-b882fb63f3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-text required</value>
      <webElementGuid>9cb1d12d-22fb-405d-9b59-3e45583ab723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a5d11c11-cbf4-46b5-8297-0c442a1a2c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-captcha-response&quot;)</value>
      <webElementGuid>4f9384cc-1cc7-4863-9ea9-5f03cba502c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-captcha-response']</value>
      <webElementGuid>361afb11-5832-4f03-9536-2a9b8f3c011d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-actions']/fieldset/div/div[2]/input</value>
      <webElementGuid>30161006-30b0-4453-b0d6-0bbbce2042ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[2]/input</value>
      <webElementGuid>214254f1-5d21-4dce-b741-bbf14b0e5341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'edit-captcha-response' and @name = 'captcha_response']</value>
      <webElementGuid>242ba161-63ec-45a7-a960-6737acf73005</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
