<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__field_reg_positionund0value</name>
   <tag></tag>
   <elementGuidId>6375f0e5-98dd-4292-b6bd-bd4b32b01f00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-field-reg-position-und-0-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit-field-reg-position-und-0-value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ada43215-d27c-4558-95f2-67160a6ad237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-full form-text</value>
      <webElementGuid>94a4caa4-69f5-4b6b-992f-43e7eb01969f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6544fe2e-9288-4d86-8170-476db47a9788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-field-reg-position-und-0-value</value>
      <webElementGuid>72d744de-de6d-4aba-a6f8-27364cf89ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_reg_position[und][0][value]</value>
      <webElementGuid>19bad6cb-2fa0-4b24-bce4-488142998759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>fe22f4f0-52cb-4e03-a1de-e72a7101ffce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>153d3a35-e562-4ec1-8080-f69f72b0e9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-field-reg-position-und-0-value&quot;)</value>
      <webElementGuid>93ebc197-5baf-47c7-a20d-e731bf4d95a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-field-reg-position-und-0-value']</value>
      <webElementGuid>e2016182-90a6-4f51-a6d0-046f83566e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-reg-position-add-more-wrapper']/div/input</value>
      <webElementGuid>be0de45b-19a4-49bd-8969-6feeb0f0311b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>f414699a-a15d-447d-9187-36dacc0dd3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'edit-field-reg-position-und-0-value' and @name = 'field_reg_position[und][0][value]']</value>
      <webElementGuid>8a4451d0-f453-4155-b6e7-3be873056949</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
