<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__field_reg_mobileund0value</name>
   <tag></tag>
   <elementGuidId>69b54a77-2bf2-4002-8ebe-319dbe8b0e36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-field-reg-mobile-und-0-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit-field-reg-mobile-und-0-value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1fa5d78-925b-4379-9556-d1d0db466660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-full form-text required</value>
      <webElementGuid>30518f7a-3829-4e71-861b-e8e78685030f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>503d1483-d0e2-48de-9d64-73c093511845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-field-reg-mobile-und-0-value</value>
      <webElementGuid>21417300-5ce5-473e-95c3-6ea59dcdf0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_reg_mobile[und][0][value]</value>
      <webElementGuid>3e33efc2-6722-4b92-8533-6a983739444f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>4eca0144-5c48-4261-82e6-4f44b04e4e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>3879a67c-af38-46bd-b51c-9e11e70b0f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-field-reg-mobile-und-0-value&quot;)</value>
      <webElementGuid>8431fa45-d194-47ed-9bbd-25a966765ec5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-field-reg-mobile-und-0-value']</value>
      <webElementGuid>d92abde6-c0f0-4d31-b93d-b71fa12eef3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-reg-mobile-add-more-wrapper']/div/input</value>
      <webElementGuid>4f6fc893-d5d6-41fd-b3f5-55f219491e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>40d70fa7-dac4-4da2-90c8-f65998eefe73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'edit-field-reg-mobile-und-0-value' and @name = 'field_reg_mobile[und][0][value]']</value>
      <webElementGuid>e430925d-8db8-4ea2-8953-6263217e6046</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
