<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- None - AI Builder in Power Platfor_361b95</name>
   <tag></tag>
   <elementGuidId>474475a9-157e-4a33-95bd-dba6bf0f08b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-field-reg-course-und</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='edit-field-reg-course-und']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>78315103-e83d-48fe-9cb9-a6276ae22ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-field-reg-course-und</value>
      <webElementGuid>cd0b3d2e-6bd9-48a3-92ca-d0606dc3df71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_reg_course[und]</value>
      <webElementGuid>c9f0e227-d4f0-4628-8654-f1857d26b965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>b8e3717f-9ded-4924-9844-550c45e928b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- None - AI Builder in Power Platform for Business (PP-AI)  Amazon Web Service (AWS) (AWS-L1)  ASP.NET Core MVC (DEV-VS-04)  ASP.NET Core Web API &amp; Security (DEV-VS-06)  ASP.NET MVC 5 with Visual Studio (DEV-VS-03)  ASP.NET Web Development with Visual Studio (DEV-VS-02)  Build Power Apps with Power Automate (POWER-PF-B1)  Data Analysis Expression (DAX) for Power BI (POWER-BI-DAX)  Data Model for Power BI (POWER-BI-XDM)  Database Concept and Design (DB-01)  ETL with SQL Server Integration Service (SSIS) (SQL-BI-ETL)  Google Document and Cloud Solutions for groups and business (GOO-01)  Infographics &amp; Digital Media with Advanced Microsoft PowerPoint (MSP-L3)  Innovation Anywhere with Microsoft Power Platform (POWER-PF)  Machine Learning using Python (PYTHON-L2)  Microsoft 365 for Business (MS365-L1)  Microsoft Access Advanced and Macro (MSA-L2)  Microsoft Access Intermediate (MSA-L1)  Microsoft Access VBA (MSA-L3)  Microsoft Excel Advanced (MSE-L2)  Microsoft Excel Advanced for Financial (MSE-FINANCE)  Microsoft Excel Advanced PivotTable and PivotChart (MSE-L4)  Microsoft Excel Business Intelligence (MSE-L5)  Microsoft Excel Intermediate (MSE-L1)  Microsoft Excel Macro and VBA (MSE-L3)  Microsoft Excel Power Query (MSE-L6)  Microsoft Excel Powerful Functions (MSE-FUNCTIONS)  Microsoft Excel VBA Programming (MSE-L7)  Microsoft PowerPoint Advanced (MSP-L1)  Microsoft PowerPoint Design in Action (MSP-L2)  Microsoft Project Managing Projects (MSJ-L1)  Microsoft SQL Server Business Intelligence (MS-SQL-19-BI-L1)  Microsoft SQL Server Database Administration (SQL-ADM)  Microsoft SQL Server Database Development (MS-SQL-19-DEV)  Microsoft SQL Server Database Queries (MS-SQL-19-QUERY)  Microsoft SQL Server Essential (SQL-101)  Microsoft SQL Server Performance Tuning (SQL-ADM-Tuning)  Microsoft Word Professional (MSWO365-PRO)  Multi-Dimension Data Model with SQL Server Analysis Service (SSAS) (SQL-BI-MDM)  Power Apps for Business (Power-Apps)  Power Automate (Cloud) for Business Automation (PAM-CLD)  Power Automate (Desktop) for Business Automation (PAM-DSK)  Power BI Advanced Visualization and AI (POWER-BI-ADV)  Power BI Advanced Power Query (POWER-BI-PQ)  Power BI Desktop for Business Analytics (POWER-BI)  Professional SQL Server Database Backup (SQL-ADM-BK)  Programming in C# with Visual Studio (DEV-VS-01)  Provisioning SQL Server and SQL Azure (MS-SQL-19-Prov)  Python Programming (PYTHON-L1)  Querying Data with T-SQL (SQL-PG-Query)  Responsive Web Design with Bootstrap 4 (DEV-BT)  SQL Server Agent and PowerShell for Automation Tasks (SQL-ADM-AGT)  SQL Server Programming - Stored Procedure (SQL-PG-SP)  SQL Server Security Management (SQL-ADM-Secure)  SQL Server Table Structure and Index (SQL-PG-TBIX)  Tabular Data Model with SQL Server Analysis Service (SSAS) (SQL-BI-TDM)  UiPath for Business Automation (UIPATH)  Xamarin Forms : การพัฒนา Native Cross-platform Apps ด้วย C# (DEV-VS-05) </value>
      <webElementGuid>1de11ef2-d0d4-4a56-a74a-6538fc3d106d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-field-reg-course-und&quot;)</value>
      <webElementGuid>b3367d5f-b8f6-4786-ae52-286c43783900</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='edit-field-reg-course-und']</value>
      <webElementGuid>0266c02c-d4e2-4c09-a62a-196528b15e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-field-reg-course']/div/select</value>
      <webElementGuid>74b58fd6-67e3-4a60-af3b-b5e8c56b939d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='หลักสูตร'])[2]/following::select[1]</value>
      <webElementGuid>11d3eebd-19d6-47f0-b888-8bc5c93acda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='หลักสูตรอื่นๆ'])[1]/following::select[1]</value>
      <webElementGuid>34b6fa2c-ed19-44c1-88e5-8114919e3339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='กรุณาใส่ชื่อหลักสูตรที่ต้องการฝึกอบรม เช่น Excel, SQL Server เป็นต้น'])[1]/preceding::select[1]</value>
      <webElementGuid>c915fffb-8811-4b28-b5d2-92a69adcc859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='หลักสูตรอื่นๆ'])[2]/preceding::select[1]</value>
      <webElementGuid>6dcb0ce2-7597-4749-ba65-6989c5da7436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>2c6f8dd7-6346-4617-82e2-f797681170a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'edit-field-reg-course-und' and @name = 'field_reg_course[und]' and (text() = '- None - AI Builder in Power Platform for Business (PP-AI)  Amazon Web Service (AWS) (AWS-L1)  ASP.NET Core MVC (DEV-VS-04)  ASP.NET Core Web API &amp; Security (DEV-VS-06)  ASP.NET MVC 5 with Visual Studio (DEV-VS-03)  ASP.NET Web Development with Visual Studio (DEV-VS-02)  Build Power Apps with Power Automate (POWER-PF-B1)  Data Analysis Expression (DAX) for Power BI (POWER-BI-DAX)  Data Model for Power BI (POWER-BI-XDM)  Database Concept and Design (DB-01)  ETL with SQL Server Integration Service (SSIS) (SQL-BI-ETL)  Google Document and Cloud Solutions for groups and business (GOO-01)  Infographics &amp; Digital Media with Advanced Microsoft PowerPoint (MSP-L3)  Innovation Anywhere with Microsoft Power Platform (POWER-PF)  Machine Learning using Python (PYTHON-L2)  Microsoft 365 for Business (MS365-L1)  Microsoft Access Advanced and Macro (MSA-L2)  Microsoft Access Intermediate (MSA-L1)  Microsoft Access VBA (MSA-L3)  Microsoft Excel Advanced (MSE-L2)  Microsoft Excel Advanced for Financial (MSE-FINANCE)  Microsoft Excel Advanced PivotTable and PivotChart (MSE-L4)  Microsoft Excel Business Intelligence (MSE-L5)  Microsoft Excel Intermediate (MSE-L1)  Microsoft Excel Macro and VBA (MSE-L3)  Microsoft Excel Power Query (MSE-L6)  Microsoft Excel Powerful Functions (MSE-FUNCTIONS)  Microsoft Excel VBA Programming (MSE-L7)  Microsoft PowerPoint Advanced (MSP-L1)  Microsoft PowerPoint Design in Action (MSP-L2)  Microsoft Project Managing Projects (MSJ-L1)  Microsoft SQL Server Business Intelligence (MS-SQL-19-BI-L1)  Microsoft SQL Server Database Administration (SQL-ADM)  Microsoft SQL Server Database Development (MS-SQL-19-DEV)  Microsoft SQL Server Database Queries (MS-SQL-19-QUERY)  Microsoft SQL Server Essential (SQL-101)  Microsoft SQL Server Performance Tuning (SQL-ADM-Tuning)  Microsoft Word Professional (MSWO365-PRO)  Multi-Dimension Data Model with SQL Server Analysis Service (SSAS) (SQL-BI-MDM)  Power Apps for Business (Power-Apps)  Power Automate (Cloud) for Business Automation (PAM-CLD)  Power Automate (Desktop) for Business Automation (PAM-DSK)  Power BI Advanced Visualization and AI (POWER-BI-ADV)  Power BI Advanced Power Query (POWER-BI-PQ)  Power BI Desktop for Business Analytics (POWER-BI)  Professional SQL Server Database Backup (SQL-ADM-BK)  Programming in C# with Visual Studio (DEV-VS-01)  Provisioning SQL Server and SQL Azure (MS-SQL-19-Prov)  Python Programming (PYTHON-L1)  Querying Data with T-SQL (SQL-PG-Query)  Responsive Web Design with Bootstrap 4 (DEV-BT)  SQL Server Agent and PowerShell for Automation Tasks (SQL-ADM-AGT)  SQL Server Programming - Stored Procedure (SQL-PG-SP)  SQL Server Security Management (SQL-ADM-Secure)  SQL Server Table Structure and Index (SQL-PG-TBIX)  Tabular Data Model with SQL Server Analysis Service (SSAS) (SQL-BI-TDM)  UiPath for Business Automation (UIPATH)  Xamarin Forms : การพัฒนา Native Cross-platform Apps ด้วย C# (DEV-VS-05) ' or . = '- None - AI Builder in Power Platform for Business (PP-AI)  Amazon Web Service (AWS) (AWS-L1)  ASP.NET Core MVC (DEV-VS-04)  ASP.NET Core Web API &amp; Security (DEV-VS-06)  ASP.NET MVC 5 with Visual Studio (DEV-VS-03)  ASP.NET Web Development with Visual Studio (DEV-VS-02)  Build Power Apps with Power Automate (POWER-PF-B1)  Data Analysis Expression (DAX) for Power BI (POWER-BI-DAX)  Data Model for Power BI (POWER-BI-XDM)  Database Concept and Design (DB-01)  ETL with SQL Server Integration Service (SSIS) (SQL-BI-ETL)  Google Document and Cloud Solutions for groups and business (GOO-01)  Infographics &amp; Digital Media with Advanced Microsoft PowerPoint (MSP-L3)  Innovation Anywhere with Microsoft Power Platform (POWER-PF)  Machine Learning using Python (PYTHON-L2)  Microsoft 365 for Business (MS365-L1)  Microsoft Access Advanced and Macro (MSA-L2)  Microsoft Access Intermediate (MSA-L1)  Microsoft Access VBA (MSA-L3)  Microsoft Excel Advanced (MSE-L2)  Microsoft Excel Advanced for Financial (MSE-FINANCE)  Microsoft Excel Advanced PivotTable and PivotChart (MSE-L4)  Microsoft Excel Business Intelligence (MSE-L5)  Microsoft Excel Intermediate (MSE-L1)  Microsoft Excel Macro and VBA (MSE-L3)  Microsoft Excel Power Query (MSE-L6)  Microsoft Excel Powerful Functions (MSE-FUNCTIONS)  Microsoft Excel VBA Programming (MSE-L7)  Microsoft PowerPoint Advanced (MSP-L1)  Microsoft PowerPoint Design in Action (MSP-L2)  Microsoft Project Managing Projects (MSJ-L1)  Microsoft SQL Server Business Intelligence (MS-SQL-19-BI-L1)  Microsoft SQL Server Database Administration (SQL-ADM)  Microsoft SQL Server Database Development (MS-SQL-19-DEV)  Microsoft SQL Server Database Queries (MS-SQL-19-QUERY)  Microsoft SQL Server Essential (SQL-101)  Microsoft SQL Server Performance Tuning (SQL-ADM-Tuning)  Microsoft Word Professional (MSWO365-PRO)  Multi-Dimension Data Model with SQL Server Analysis Service (SSAS) (SQL-BI-MDM)  Power Apps for Business (Power-Apps)  Power Automate (Cloud) for Business Automation (PAM-CLD)  Power Automate (Desktop) for Business Automation (PAM-DSK)  Power BI Advanced Visualization and AI (POWER-BI-ADV)  Power BI Advanced Power Query (POWER-BI-PQ)  Power BI Desktop for Business Analytics (POWER-BI)  Professional SQL Server Database Backup (SQL-ADM-BK)  Programming in C# with Visual Studio (DEV-VS-01)  Provisioning SQL Server and SQL Azure (MS-SQL-19-Prov)  Python Programming (PYTHON-L1)  Querying Data with T-SQL (SQL-PG-Query)  Responsive Web Design with Bootstrap 4 (DEV-BT)  SQL Server Agent and PowerShell for Automation Tasks (SQL-ADM-AGT)  SQL Server Programming - Stored Procedure (SQL-PG-SP)  SQL Server Security Management (SQL-ADM-Secure)  SQL Server Table Structure and Index (SQL-PG-TBIX)  Tabular Data Model with SQL Server Analysis Service (SSAS) (SQL-BI-TDM)  UiPath for Business Automation (UIPATH)  Xamarin Forms : การพัฒนา Native Cross-platform Apps ด้วย C# (DEV-VS-05) ')]</value>
      <webElementGuid>ea53dd3b-3d4f-455a-b9c7-ad6c30621b88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
