<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__field_reg_notesund0value</name>
   <tag></tag>
   <elementGuidId>2ac482b6-5ece-4acd-9585-0c6976cf057e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-field-reg-notes-und-0-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='edit-field-reg-notes-und-0-value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7d4639b8-ca0a-4657-8c3e-dbd1521557f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-full form-textarea</value>
      <webElementGuid>63a23dc8-0594-46eb-aba6-0c86428b9874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-field-reg-notes-und-0-value</value>
      <webElementGuid>aee5d352-53af-4946-ae96-47d9e835cf50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_reg_notes[und][0][value]</value>
      <webElementGuid>8fdb5aa3-9603-4f11-bb77-1fccd3d21889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>53369adb-7832-4830-a3d4-4f3950846571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e3e3ec97-e1e1-45f5-a886-1d2243161631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-field-reg-notes-und-0-value&quot;)</value>
      <webElementGuid>7eefd28b-ee80-4c38-8fae-86a91f6a8c89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='edit-field-reg-notes-und-0-value']</value>
      <webElementGuid>7066dddc-3853-4748-ae1d-e6451ed63f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-reg-notes-add-more-wrapper']/div/div/textarea</value>
      <webElementGuid>dacdcab6-e241-4144-9ac8-95a5b861c352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/textarea</value>
      <webElementGuid>e3d2aa81-d097-494c-9176-db56110a1f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'edit-field-reg-notes-und-0-value' and @name = 'field_reg_notes[und][0][value]']</value>
      <webElementGuid>5dc60b47-4b09-4f8f-a1e8-23dc7a853dfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
