<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__field_reg_address_receiptund0value</name>
   <tag></tag>
   <elementGuidId>a4ffe7a1-a634-4d09-9a33-a73bd90cba7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-field-reg-address-receipt-und-0-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='edit-field-reg-address-receipt-und-0-value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>cb44b1f6-70e0-4d91-84c5-30ffa735d614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-full form-textarea</value>
      <webElementGuid>af8f42be-a60e-4f4b-9e14-1bbe59e3ecb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-field-reg-address-receipt-und-0-value</value>
      <webElementGuid>4cc07f68-023b-477f-a26c-547575174c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_reg_address_receipt[und][0][value]</value>
      <webElementGuid>431334d9-8f18-4603-af38-67d119cd4f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>95062801-b3d5-4e43-846e-7539d9e3848a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>49a27ef7-d257-489f-ae09-830e3418af22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-field-reg-address-receipt-und-0-value&quot;)</value>
      <webElementGuid>506de1d0-c792-4742-8277-8fc700af1ada</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='edit-field-reg-address-receipt-und-0-value']</value>
      <webElementGuid>3001477f-6f37-4270-b803-d1b11e85818e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-reg-address-receipt-add-more-wrapper']/div/div/textarea</value>
      <webElementGuid>75a13aa3-e1cf-4bd4-aedd-ce322966d26f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/textarea</value>
      <webElementGuid>398eb4e9-c4b8-48fc-a42e-968b2561c256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'edit-field-reg-address-receipt-und-0-value' and @name = 'field_reg_address_receipt[und][0][value]']</value>
      <webElementGuid>c2b4ff88-c7a7-4061-9791-af68624f137b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
