<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__field_reg_locationund0value</name>
   <tag></tag>
   <elementGuidId>828ae383-0065-48d8-ab51-5b0fc74cf174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-field-reg-location-und-0-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='edit-field-reg-location-und-0-value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>85a6bfdc-3c93-4551-9b56-375f9a560cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-full form-textarea required error</value>
      <webElementGuid>d667bd4b-8589-42dc-8ffa-029183ecdbc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-field-reg-location-und-0-value</value>
      <webElementGuid>b943ae31-bed3-440a-8644-7096ccd77945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_reg_location[und][0][value]</value>
      <webElementGuid>b05d88d0-767b-4501-bab9-b63340f87e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>14d00885-f42e-40a0-9b41-f266a33de03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>3aec2123-c2e6-431a-86d3-02aa7bab91af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-field-reg-location-und-0-value&quot;)</value>
      <webElementGuid>25f893b6-3f5c-4627-a065-2f6084c9860b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='edit-field-reg-location-und-0-value']</value>
      <webElementGuid>d59aaaad-e370-4c01-b61c-b1b592141fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-reg-location-add-more-wrapper']/div/div/textarea</value>
      <webElementGuid>ccf3bf59-e2fb-4e83-820e-53082b3b5a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>edadb82d-a116-46b2-bfe0-25508155efe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'edit-field-reg-location-und-0-value' and @name = 'field_reg_location[und][0][value]']</value>
      <webElementGuid>81266f9f-9b50-42e3-bf4e-69a13432da15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
